require("dotenv/config");


const {
  BCRYPT_SALT,
  JWT_SECRET,
  MONGODB_URL_DEV,
  MONGODB_URL_PROD,
  FIREBASE_APIKEY,
  FIREBASE_AUTHDOMAIN,
  FIREBASE_PROJECTID,
  FIREBASE_STORAGEBUCKET,
  FIREBASE_MESSAGESENDERID,
  FIREBASE_APPID
} = process.env;

const credentials = [
  "BCRYPT_SALT",
  "JWT_SECRET",
  "MONGODB_URL_DEV",
  "MONGODB_URL_PROD",
  "FIREBASE_APIKEY",
  "FIREBASE_AUTHDOMAIN",
  "FIREBASE_PROJECTID",
  "FIREBASE_STORAGEBUCKET",
  "FIREBASE_MESSAGESENDERID",
  "FIREBASE_APPID"
];

for (const credential of credentials) {
  if (process.env[credential] === undefined) {
    console.log(`Missing required credential ${credential}`);
    process.exit(1);
  }
}

module.exports = {
  BCRYPT_SALT,
  JWT_SECRET,
  MONGODB_URL_DEV,
  MONGODB_URL_PROD,
  FIREBASE_APIKEY,
  FIREBASE_AUTHDOMAIN,
  FIREBASE_PROJECTID,
  FIREBASE_STORAGEBUCKET,
  FIREBASE_MESSAGESENDERID,
  FIREBASE_APPID
};
